name: Linting, Testing, Building
run-name: ${{ github.actor }} is running out GitHub Actions 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-2019]
        node-version: [17.x]
        runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          fetch-depth: 0
          node_version: ${{ matrix.node-version }}
      - name: install moduless
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: linting testing
        run: npm run test:unit
      - name: linting scss
        run: npm run lint:scss
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci
